"""Initial Migration

Revision ID: 47c12f754bef
Revises: 7325244f7325
Create Date: 2021-09-25 18:14:06.358800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47c12f754bef'
down_revision = '7325244f7325'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('bio', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('profile_pic_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile_pic_path')
    op.drop_column('user', 'bio')
    # ### end Alembic commands ###
