"""Initial Migration

Revision ID: 7325244f7325
Revises: 20f30a75b66b
Create Date: 2021-09-25 13:55:58.071642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7325244f7325'
down_revision = '20f30a75b66b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.String(length=150), nullable=True))
    op.add_column('user', sa.Column('date_created', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint(None, 'user', ['username'])
    op.drop_column('user', 'first_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'date_created')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###
